const types = {
  GET_POST: "GET_POST",
  GET_POST_SUCCESS: "GET_POST_SUCCESS",
  GET_POST_FAILED: "GET_POST_FAILED",

  GET_POSTS: "GET_POSTS",
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  GET_POSTS_FAILED: "GET_POSTS_FAILED",

  GET_USER_POSTS: "GET_USER_POSTS",
  GET_USER_POSTS_SUCCESS: "GET_USER_POSTS_SUCCESS",
  GET_USER_POSTS_FAILED: "GET_USER_POSTS_FAILED",

  POST_POST: "POST_POST",
  POST_POST_SUCCESS: "POST_POST_SUCCESS",
  POST_POST_FAILED: "POST_POST_FAILED",

  UPDATE_POST: "UPDATE_POST",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  UPDATE_POST_FAILED: "UPDATE_POST_FAILED",

  DELETE_POST: "DELETE_POST",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAILED: "DELETE_POST_FAILED",
};

export default types;
