const types = {
    GET_MESSAGES: 'GET_MESSAGES',
    GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
    GET_MESSAGES_FAILED: 'GET_MESSAGES_FAILED',

    POST_MESSAGES: 'POST_MESSAGES',
    POST_MESSAGES_SUCCESS: 'POST_MESSAGES_SUCCESS',
    POST_MESSAGES_FAILED: 'POST_MESSAGES_FAILED',
};

export default types;
