const types = {
    GET_MESSAGES: 'GET_MESSAGES',
    GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
    GET_MESSAGES_FAILED: 'GET_MESSAGES_FAILED',

    POST_MESSAGES: 'POST_MESSAGES',
    POST_MESSAGES_SUCCESS: 'POST_MESSAGES_SUCCESS',
    POST_MESSAGES_FAILED: 'POST_MESSAGES_FAILED',

    DELETE_MESSAGES: 'DELETE_MESSAGES',
    DELETE_MESSAGES_SUCCESS: 'DELETE_MESSAGES_SUCCESS',
    DELETE_MESSAGES_FAILED: 'DELETE_MESSAGES_FAILED',

    VOICE_MESSAGES: 'VOICE_MESSAGES',
    VOICE_MESSAGES_SUCCESS: 'VOICE_MESSAGES_SUCCESS',
    VOICE_MESSAGES_FAILED: 'VOICE_MESSAGES_FAILED',
};

export default types;
