const types = {
    UPDATE_USER_STATUS: 'UPDATE_USER_STATUS',
    ADD_MESSAGE: 'ADD_MESSAGE',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
    ALL_LAST_MESSAGES: 'ALL_LAST_MESSAGES',
    DELETE_ROOM: 'DELETE_ROOM',
    CHANGE_MESSAGE: 'CHANGE_MESSAGE',
};

export default types;
