const types = {
  UPLOAD_FILE: "UPLOAD_FILE",
  UPLOAD_FILE_SUCCESS: "UPLOAD_FILE_SUCCESS",
  UPLOAD_FILE_FAILED: "UPLOAD_FILE_FAILED",

  UPLOAD_AVATAR: "UPLOAD_AVATAR",
  UPLOAD_AVATAR_SUCCESS: "UPLOAD_AVATAR_SUCCESS",
  UPLOAD_AVATAR_FAILED: "UPLOAD_AVATAR_FAILED",

};

export default types;
