const types = {
    GET_ROOM: 'GET_ROOM',
    GET_ROOM_SUCCESS: 'GET_ROOM_SUCCESS',
    GET_ROOM_FAILED: 'GET_ROOM_FAILED',

    POST_ROOM: 'POST_ROOM',
    POST_ROOM_SUCCESS: 'POST_ROOM_SUCCESS',
    POST_ROOM_FAILED: 'POST_ROOM_FAILED',

    POST_GROUP_ROOM: 'POST_GROUP_ROOM',
    POST_GROUP_ROOM_SUCCESS: 'POST_GROUP_ROOM_SUCCESS',
    POST_GROUP_ROOM_FAILED: 'POST_GROUP_ROOM_FAILED',
};

export default types;
