const types = {
  POST: "POST",
  POST_SUCCESS: "POST_SUCCESS",
  POST_FAILED: "POST_FAILED",

  GET: "GET",
  GET_SUCCESS: "GET_SUCCESS",
  GET_FAILED: "GET_FAILED",

  DELETE: "DELETE",
  DELETE_SUCCESS: "DELETE_SUCCESS",
  DELETE_FAILED: "DELETE_FAILED",

};

export default types;
