const types = {
  GET_USER: "GET_USER",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAILED: "GET_USER_FAILED",

  GET_OTHER_USER: "GET_OTHER_USER",
  GET_OTHER_USER_SUCCESS: "GET_OTHER_USER_SUCCESS",
  GET_OTHER_USER_FAILED: "GET_OTHER_USER_FAILED",

  GET_USERS: "GET_USERS",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAILED: "GET_USERS_FAILED",
};

export default types;
